functions = {
    "command": {"id": 1},
    "getlastcommands": {"id": 2},
    "getcalibrationnames": {"id": 3},
    "getfitnames": {"id": 4},
    "getcalibration": {"id": 5},
    "setrawcalibration": {"id": 6},
    "setfitcalibrations": {"id": 7},
    "setactiveodcal": {"id": 8},
    "getactivecal": {"id": 9},
    "getdevicename": {"id": 10},
    "setdevicename": {"id": 11},
    "run_commands": {"id": 12},
    "get_num_commands": {"id": 13},
    "sub_command": {"id": 14},
}
